dolezsa/thermal_comfort

custom_components/thermal_comfort/sensor.py

Fixes #1 
When the designated temperature sensor has values in Fahrenheit, make sure to convert to Celsius so that the calculations work correctly.

Convert to C from F when reading temp

---

README.md
custom_components/thermal_comfort/sensor.py

This adds the optional configuration variable unique_id to the sensor
platform. This allows the user to set a unique_id per sensor, the
sensor_type of each entity is added to make it unique per entity.
If this is set, it allows to partially manage the entities from the UI
without enabling the advanced mode. Specifically, this allows to use the
Area setting, which is used in the default Lovelace Dashboard.
Note: This also includes a small reformatting change, there was mixed intent in line 12-13, those had tabs, i replaced them with spaces to match the rest of the file.

sensor: implement unique_id for yaml config

---

custom_components/thermal_comfort/sensor.py

This adds a NaN check for temperature and input sensors so we don't pass
them on to hass and prevent lovelace from loading. Fixes #19
Also move the common state check into _is_valid_state helper functions.

sensor: check for nan values from input states

---

custom_components/thermal_comfort/sensor.py

Check for None instead of just the boolean value of self._temperature
and self._humidity since bool(0.0) == False, which is not intended.
Fixes #24

sensor: fix check for None on async_update

---

custom_components/thermal_comfort/sensor.py
custom_components/thermal_comfort/translations/sensor.de.json
custom_components/thermal_comfort/translations/sensor.en.json

Move dewpoint thermal perception strings to translation files and use
keyword constants instead.
Also simplify some states since there meaning gets lost when the
scientific model, especially the boundaries in this case, isn't known
to the user. E.g. remove mentioning of the upper edge which is unknown
to the user.
This fixes #17 since it should be easy for others to add translations
now.

sensor: add en and de translation files

---

custom_components/thermal_comfort/sensor.py

This replaces properties with the corresponding attr to be more inline
with hass upstream. Also replace device_state_attributes with
extra_state_attributes which fixes #30

Use attr instead of properties in sensor platform

---

README.md
custom_components/thermal_comfort/sensor.py
tests/test_sensor.py

Cherry pick 0717395dc9e9c41c09abedf88876359ed7a1b045 to add support for sensor_types config which allows to create only some sensors. Add corresponding test case.
Fixes #7

Sensor types

---

custom_components/thermal_comfort/sensor.py
tests/test_sensor.py

Don't check for both strings and floats in a tuple. Make _is_valid_state
more expressive and add corresponding tests.
Fixes #37

Fix check for float in tuple

---

README.md
custom_components/thermal_comfort/sensor.py
custom_components/thermal_comfort/translations/sensor.de.json
custom_components/thermal_comfort/translations/sensor.en.json
custom_components/thermal_comfort/translations/sensor.fr.json
custom_components/thermal_comfort/translations/sensor.it.json
tests/test_sensor.py

Sorry for doing another PR, had some trouble with rebasing on the last one.
This adds both a frost point and a frost risk sensor as default sensors
to the sensor platform. Both are based on @papo-o's functions, which
where provided by them. See also his fork of thermal comfort for this
sensors https://github.com/papo-o/home-assistant-frost-risks.
See #36
Currently this adds the two new sensors as default because the expected behavior for 1.0.0 is to add all sensors if this config variable is not explicitly set. So it may be confusing for users if we just derivative from that behavior now.

Add frost point and frost risk sensors

---

custom_components/thermal_comfort/__init__.py
custom_components/thermal_comfort/config_flow.py
custom_components/thermal_comfort/const.py
custom_components/thermal_comfort/manifest.json
custom_components/thermal_comfort/sensor.py
custom_components/thermal_comfort/translations/en.json
tests/const.py
tests/test_config_flow.py
tests/test_init.py
tests/test_sensor.py

- added config flow
- sensor module refactoring:
- move necessary const to const
- create common sensor to support configuration via .yaml and UI at same time
For future improving:
1. check user input:
- temperature sensor muse have temperature unit of measurement
- humidity sensor must have humidity unit of measurement
2. replace direct sensor input by dropdown list of suitable sensors
Fix #73

feat: configure integration via UI

---

custom_components/thermal_comfort/__init__.py
custom_components/thermal_comfort/config.py
custom_components/thermal_comfort/sensor.py
custom_components/thermal_comfort/services.yaml
tests/conftest.py
tests/test_config_flow.py
tests/test_sensor.py

This adds async_setup to the thermal_comfort integration and allows to
setup the platforms under integration domain key.
e.g.
```yaml
thermal_comfort:
- sensor:
- temperature_sensor: sensor.kitchen_temperature
humidity_sensor: sensor.kitchen_humidity
```
With this commit the thermal_comfort integration supports both the old
legacy configuration under the platform key e.g. sensor and the new
configuration under integration domain key.
The `friendly_name` config key has been renamed to `name` and takes up
the role as both friendly name and identifier = entity_id.
This requires user intervention when converting the old
configurations to new ones.
e.g.
```yaml
sensor:
- platform: thermal_comfort
sensors:
old_kitchen:
friendly_name: Old Kitchen
temperature_sensor: sensor.kitchen_temperature …
```

New yaml config

---

custom_components/thermal_comfort/const.py
custom_components/thermal_comfort/sensor.py

Simpler approach for #97 using built in methods. This avoids to use filesystem io during device creation.

Get device/integration version from manifest

---

custom_components/thermal_comfort/sensor.py
custom_components/thermal_comfort/translations/en.json
tests/test_sensor.py

This splits up all sensor types into seperate words for readability and
string manipulation. Currently this is implemented in a backward
compatible way.
The new sensor type names are separated by a underscore
`_`. e.g. `dew_point`.
The old sensor names are called shortform and are available through
SensorType.TYPE.shortform(). The shortform is still used in places where
it otherwise would cause a user breaking change. e.g. entity_id
SensorType also offers a from_shortform constructor so we can support
the old shortform in yaml for the sensor_types list.
SensorType also offers a to_title() method which creates replaces the
underscore with a space and capitalizes the first letters of every word.
e.g. used in sensor names.

Rename sensor types

---

custom_components/thermal_comfort/__init__.py
custom_components/thermal_comfort/config_flow.py
custom_components/thermal_comfort/sensor.py
custom_components/thermal_comfort/translations/en.json
tests/const.py

The custom_icons option which defaults to false allows to use the icons
from the thermal_comfort_icons pack as default icons when enabled.
https://github.com/rautesamtr/thermal_comfort_icons/
closes #101

Add custom_icons option to the sensor platform

---

custom_components/thermal_comfort/config_flow.py
tests/test_config_flow.py

While configuration it is comfortable just to click at sensor.
Allow user doing this.
Not all sensors may be in device registry, but we can't check sensors out of registry. We should not limit advanced users in their choose (just because if root tries `rm -rf /`, it should be root problem, not OS), but should help ordinary users.
Alternative version of #105

feat: add sensor selection from list in configuration via UI

---

custom_components/thermal_comfort/config_flow.py

If user is not in advanced mode default sensor should be added to user input before entity creation.
Fixes #108

fix(UI configuration): enable default sensors in simple mode

---

custom_components/thermal_comfort/__init__.py
custom_components/thermal_comfort/config_flow.py
custom_components/thermal_comfort/sensor.py
custom_components/thermal_comfort/translations/de.json
custom_components/thermal_comfort/translations/en.json
tests/const.py
tests/test_config_flow.py
tests/test_init.py
tests/test_sensor.py

This changes the config flow entity setup to only set
entity_registry_enabled_default only once. After that it is managed by
the entity registry.
This also changes the selection of the enabled sensor types to a
multichoice. We loose translation for the sensor type itself, but we get
a cleaner and more usable interface for advanced users.
Tests where fixed and some variables renamed to make them more
descriptive.

Disable config flow entities only once

---

.pre-commit-config.yaml
custom_components/thermal_comfort/config_flow.py
custom_components/thermal_comfort/translations/de.json
custom_components/thermal_comfort/translations/en.json

Abort config flow with error message if no input sensors are available.

Fix config flow crash on empty sensor lists 

---

custom_components/thermal_comfort/sensor.py
tests/test_sensor.py

Instead of just returning a string if sensor_type is not a shortform
but correct sensor name return a SensorType as expected.
Add corresponding test case.
fixes #115

Correctly handle sensor type from string

---

custom_components/thermal_comfort/config_flow.py
custom_components/thermal_comfort/sensor.py

Use defaults for scan_interval while `async_setup_entry`.
It prevent crashes like
```
2022-02-01 18:47:34 DEBUG (MainThread) [custom_components.thermal_comfort.sensor] async_setup_entry: {'name': 'Thermal Comfort livingroom', 'temperature_sensor': 'sensor.livingroomsensorsbed_bme280_temperature', 'humidity_sensor': 'sensor.livingroomsensorsbed_bme280_humidity', 'poll': False, 'scan_interval': None, 'custom_icons': None, 'update_listener': <function ConfigEntry.add_update_listener.<locals>.<lambda> at 0xaf1da0b8>}
2022-02-01 18:47:34 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up thermal_comfort platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await …
```

Defaults for scan interval

---

custom_components/thermal_comfort/config_flow.py

We should exclude sensors with temperature units from humidity candidates and percent unit from temperature candidates
Part of #121

feat: use additional filters for humidity and temperature sensors

---

custom_components/thermal_comfort/config_flow.py

We are probably will be able to use it in the future, but not now.
Part of #121

feat: add climate domain to useless list

---

.github/workflows/add_archive_to_release.yml
hacs.json

It will:
* allow use badges like
* show downloads counters at integration page in HACS;
* simplify manual installation;

ci: add archive to release

---

custom_components/thermal_comfort/__init__.py
custom_components/thermal_comfort/config.py
custom_components/thermal_comfort/config_flow.py
custom_components/thermal_comfort/sensor.py
documentation/yaml.md
tests/test_sensor.py

This adds global options per thermal comfort platform entry. This
options are set for all entries but can be overridden per sensor entry.
Supported options are `poll`, `scan_interval`, `custom_icons`,
`sensor_types`.
e.g.
```yaml
thermal_comfort:
- poll: true
scan_interval: 5
sensor:
- name: Kitchen
…
- name: Garage
poll: false
```

Yaml global options

---

custom_components/thermal_comfort/config_flow.py

Use entity selectors for config flow for temperature and humidity
sensor. This allows for copy paste for valid entities and as you type
suggestions.

Use entity selectors in config_flow

---

custom_components/thermal_comfort/__init__.py
custom_components/thermal_comfort/sensor.py
requirements_test.txt
tests/test_init.py

Use async_forward_entry_setups instead of async_setup_platforms.
See https://developers.home-assistant.io/blog/2022/07/08/config_entry_forwards/

Migrate to async_forward_entry_setups

---

custom_components/thermal_comfort/config_flow.py
custom_components/thermal_comfort/sensor.py
tests/test_sensor.py

Only set device name and entity name for config entries.
Home assistant autogenerates entity_id and friendly name from it.
Only the first word in an entity name starts with a capital letter.
https://developers.home-assistant.io/blog/2022/07/10/entity_naming/
https://developers.home-assistant.io/docs/core/entity/#entity-naming
In the process drop shortform support for sensor type names.
Both changes make this a breaking change.

Migrate to home assistant new naming scheme

---

LICENSE
README.md
custom_components/thermal_comfort/sensor.py
documentation/yaml.md
tests/test_sensor.py

Uses code ported from pythermalcomfort and so needs an additional
copyright line in the LICENSE file.

Add moist air enthalpy sensor

---

custom_components/thermal_comfort/sensor.py

Use more default material design icons where posible.
Replace simmer index/zone icon with a default one.
The night indication contradicts with the more common description of the
Summer simmer index/zone.

Rework default icons

---

custom_components/thermal_comfort/sensor.py
tests/test_sensor.py

Add the index sensor as attribute to perception sensors of the index
that they are based on.
This also replaces the frost risk level attribute with the frost
point attribute for frost risk.

Add attributes to perception sensors

---

custom_components/thermal_comfort/sensor.py

Abort calculations if relative humidity is not larger then 0 and emit a warning on invalid temperature or relative humidity states.
Closes #198

Abort calculations with invalid relative humidity

---

custom_components/thermal_comfort/sensor.py

This is needed since sensors humidity device class only supports % as unit and raises a warning when other units are used. This will be an error in 2023.6. See https://github.com/home-assistant/core/pull/84366

Remove humidity deviceclass from absolute humidity

---

custom_components/thermal_comfort/sensor.py

This useses the enum sensor device class introduced in home assistant 2023.01. Enum sensors represent a textual state from a fixed set of possible states.

Use enum sensor device class for textual sensors

---

README.md
inlang.config.js

Let me know what changes you request for merging this PR.
This pull request adds the possibility for contributors and translators to manage translations in a UI instead of files with no overhead for the maintainers.
To get a UI for translations contained in this repository, an [inlang.config.js](https://inlang.com/documentation/config) has been created at the root of the repository. Furthermore, the translation files have been cleaned and I added a little i18n docs on the read me. If you want this to be somewhere else please let me know.
The changes of this PR and a live instance of the editor can be previewed with the following link https://inlang.com/editor/github.com/NilsJacobsen/thermal_comfort. Note: This link should be changed to point to dolezsa instead of NilsJacobsen after this …

add inlang to make the contribution of translations easier

---

custom_components/thermal_comfort/sensor.py
custom_components/thermal_comfort/translations/ca.json
custom_components/thermal_comfort/translations/da.json
custom_components/thermal_comfort/translations/de.json
custom_components/thermal_comfort/translations/el.json
custom_components/thermal_comfort/translations/en.json
custom_components/thermal_comfort/translations/es.json
custom_components/thermal_comfort/translations/fr.json
custom_components/thermal_comfort/translations/it.json
custom_components/thermal_comfort/translations/nl.json
custom_components/thermal_comfort/translations/pl.json
custom_components/thermal_comfort/translations/pt.json
custom_components/thermal_comfort/translations/ro.json
custom_components/thermal_comfort/translations/ru.json
custom_components/thermal_comfort/translations/sk.json
custom_components/thermal_comfort/translations/zh-Hans.json

https://developers.home-assistant.io/blog/2023/03/27/entity_name_translations
This PR adds support for translating sensor names. For this the `translation key` has been moved form the SENSOR_TYPES description map and is set in he SensorThermalComfort Class since every entity needs a `translation_key`. Translation works out of the box for config flow entities since we already implemented `has_entity_name` for them. It doesn't for YAML. With `has_entity_name` set to `True` and translations enabled we lose the name set for the device in YAML.
For now we only offer translations in YAML when the name isn't set.

Support translated sensor names

---

custom_components/thermal_comfort/sensor.py
tests/test_sensor.py

The moist air enthalpy calculations do not match the equations in the ASHRAE fundamentals 2021 edition. This PR fixes that and adds references to the source of each equation and uses the same naming scheme to make it easier to follow.

Fix moist air enthalpy calculation to match ASHRAE fundamentals 2021 edition

---

custom_components/thermal_comfort/sensor.py

Set fields for SensorEntityDescription before initialization since EntityDescription and SensorEntityDescription will be frozen dataclass in future home assistant releases.
https://developers.home-assistant.io/blog/2023/12/11/entity-description-changes

Refactor for frozen EntityDescription dataclass

---

custom_components/thermal_comfort/sensor.py

Moves the entity registry default enablement into sensor initialization to fix the issues with frozen dataclass. The value is set in the dictionary prior to the dataclass being initialized.

Move config entry default entity enablement

---

custom_components/thermal_comfort/config_flow.py

This causes an error when creating a new device with the extension with ha version 2024.09.0
Reference to the removal: https://github.com/home-assistant/core/pull/123741

Remove Platform.MAILBOX as its no longer supported
