dolezsa/thermal_comfort

custom_components/thermal_comfort/sensor.py
Use async_track_state_change_event instead of async_track_state_change
since this is recommended way according to the home assistant
documentation.
"If entity_ids are not MATCH_ALL along with from_state and to_state
being None, async_track_state_change_event should be used instead as
it is slightly faster."
=> Use async_track_state_change_event

custom_components/thermal_comfort/manifest.json, custom_components/thermal_comfort/sensor.py, custom_components/thermal_comfort/translations/sensor.de.json, custom_components/thermal_comfort/translations/sensor.en.json, custom_components/thermal_comfort/translations/sensor.es.json, custom_components/thermal_comfort/translations/sensor.hu.json, custom_components/thermal_comfort/translations/sensor.sk.json
This adds fixes for the Hassfest Github Action to validate the component without errors and warnings.
=> Hassfest fixes

.github/FUNDING.yml, .github/workflows/hacs.yml, .github/workflows/hassfest.yml, .github/workflows/pytest.yml, .pre-commit-config.yaml, .yamllint, custom_components/__init__.py, custom_components/thermal_comfort/__init__.py, custom_components/thermal_comfort/sensor.py, requirements_test_pre_commit.txt, setup.cfg, tests/bandit.yaml, tests/conftest.py, tests/test_sensor.py
Use home assistants pre_commit hook since this allows for code that is
easier to upstream.
=> Use home assistants pre_commit

custom_components/thermal_comfort/sensor.py
Instead of using custom toFahrenheit and toCelsius use the already
used methods from home assistant.
=> Use homeassistant.util.temperature module

README.md, custom_components/thermal_comfort/sensor.py, custom_components/thermal_comfort/translations/sensor.en.json, tests/test_sensor.py
Let's try this again! I messed up the [previous PR](https://github.com/dolezsa/thermal_comfort/pull/65) and thought it would be easier to create a new one.
This is based on another fork of thermal_comfort by @lymanepp at https://github.com/lymanepp/thermal_comfort. I adapted the code to work with this plugin. The only thing missing is the translations for the Simmer Zone strings.
=> Added Simmer Index and Simmer Zone

custom_components/thermal_comfort/sensor.py
Adds state_class: measurement for sensors supporting it. E.g.
those with temperature and humidity device class.
Fixes #74
=> Support long-term statistics

custom_components/thermal_comfort/sensor.py, tests/test_sensor.py
This splits SensorThermalComfort in two separate classes. One
computing/managing class for a set of sensors with the same input
sensors. And a class for the separate sensors.
Computing functions are now decorated so they can be called async in a
synchronized way so that a value is only recalculated once after an update
for all dependent sensors.
This should reduce duplicate calculation and update calls.
=> Split SensorThermalComfort

README.md, custom_components/thermal_comfort/sensor.py
This adds an optional poll mode wich can be enabled through a platform
configuration variable in yaml. This is implemented to avoid issues such
as #5
=> Add an optional poll mode

custom_components/thermal_comfort/manifest.json, custom_components/thermal_comfort/sensor.py
=> Fix not setting hass to templates

custom_components/thermal_comfort/const.py, custom_components/thermal_comfort/sensor.py
Add manufacturer, model and sw_version to device_info. This shows as
Virtual Device by Thermal Comfort Fimware: 1.3.1
=> Add additional device_infos

custom_components/thermal_comfort/translations/de.json, custom_components/thermal_comfort/translations/en.json
Add de translation for config flow
Update en translation for config flow
=> Update de,en translation for config flow

README.md, custom_components/thermal_comfort/manifest.json
Co-authored-by: lymanepp <lymanepp@users.noreply.github.com>
=> Fix yaml documentation and add unique_id info

custom_components/thermal_comfort/translations/sensor.ru.json
- Update Russian translations for simmer zone sensor.
- Small correction for thermal perception sensor.
=> Update Russian translations

CREDITS.md, custom_components/thermal_comfort/translations/sensor.pl.json
first version of the Polish translation. probably not perfect yet, but a good start to.. polish the strings :)
=> Added basic Polish translation

CREDITS.md, custom_components/thermal_comfort/translations/sensor.pl.json
after rethinking I've changed few words so everything sounds a little bit better, more natural and more "on point".
=> Small fixes to Polish translation

custom_components/thermal_comfort/translations/sensor.pt-BR.json
Added Brazilian Portuguese translation
=> Added Brazilian Portuguese translation to sensors

custom_components/thermal_comfort/sensor.py
There's a race condition at startup that can lead to exceptions in the HA logs. This provides a fix.
=> Avoid exceptions during startup

CREDITS.md, custom_components/thermal_comfort/translations/sensor.sv.json
Co-authored-by: Filip <9947929+filikun@users.noreply.github.com>
=> Add swedish translation

CREDITS.md, custom_components/thermal_comfort/translations/sensor.uk.json
Co-authored-by: <splin777@users.noreply.github.com>
=> Add ukrainian translation

README.md, custom_components/thermal_comfort/sensor.py, custom_components/thermal_comfort/translations/sensor.en.json, documentation/yaml.md, tests/test_sensor.py
https://revistadechimie.ro/pdf/16%20RUSANESCU%204%2019.pdf
#171
=> Add Winter and Summer Scharlau Perception Sensors

custom_components/thermal_comfort/sensor.py
Hi, this is a simple change that should fix #202 
I haven't tested this against tip, made these same modifications to sensor.py in my local copy of 1.5.2 and the warnings/errors went away on 2022.10.0.
=> Fix broken converter

custom_components/thermal_comfort/translations/ro.json, custom_components/thermal_comfort/translations/sensor.ro.json
Co-authored-by: Ovidiu Manoilescu <ovimano@gmail.com>
=> Add romanian translation

custom_components/thermal_comfort/sensor.py
Closes #128
Also degrade warnings about out of range to info.
=> Add sanity checks for humidity and temperature

custom_components/thermal_comfort/sensor.py, custom_components/thermal_comfort/translations/ca.json, custom_components/thermal_comfort/translations/cs.json, custom_components/thermal_comfort/translations/de.json, custom_components/thermal_comfort/translations/en.json, custom_components/thermal_comfort/translations/es.json, custom_components/thermal_comfort/translations/fr.json, custom_components/thermal_comfort/translations/hu.json, custom_components/thermal_comfort/translations/it.json, custom_components/thermal_comfort/translations/nb.json, custom_components/thermal_comfort/translations/nl.json, custom_components/thermal_comfort/translations/pl.json, custom_components/thermal_comfort/translations/pt-BR.json, custom_components/thermal_comfort/translations/pt.json, custom_components/thermal_comfort/translations/ro.json, custom_components/thermal_comfort/translations/ru.json, custom_components/thermal_comfort/translations/sk.json, custom_components/thermal_comfort/translations/sv.json, custom_components/thermal_comfort/translations/uk.json, documentation/yaml.md, tests/test_sensor.py
=> Sensor 2.0 renames

custom_components/thermal_comfort/__init__.py, custom_components/thermal_comfort/config_flow.py
Add migration of unique_ids for renamed sensors.
=> Add config flow version 2 migration

custom_components/thermal_comfort/translations/it.json, custom_components/thermal_comfort/translations/ro.json
Hello!
I have added translations for new sensors:
humidex_perception
relative_strain_perception
scharlau_perception
thoms_discomfort_perception
=> Update ro.json and it.json

custom_components/thermal_comfort/sensor.py, tests/test_sensor.py
Fix for https://github.com/dolezsa/thermal_comfort/issues/217
=> Fix lower limit for summer simmer index calculation

custom_components/thermal_comfort/translations/pl.json
Discomfort information slightly standarized between sensors, just to make clear what's higher and what's lower on the scale, also shortened a little bit.
=> Just a small Polish translation polishing (pun intended)

README.md, custom_components/thermal_comfort/sensor.py, hacs.json, tests/test_sensor.py
Closes #196
hold back till 2023.2 releases
=> Add native_precision sensor property for rounding

README.md, custom_components/thermal_comfort/sensor.py, hacs.json, tests/test_sensor.py
Replace the now reverted change of native_precision with suggested_display_precision.
Should fix #276
=> Use suggested_display_precision

custom_components/thermal_comfort/translations/fr.json
I added a lot of missing strings to the french translation.
=> Update french translation

custom_components/thermal_comfort/translations/ca.json, custom_components/thermal_comfort/translations/cs.json, custom_components/thermal_comfort/translations/da.json, custom_components/thermal_comfort/translations/de.json, custom_components/thermal_comfort/translations/el.json, custom_components/thermal_comfort/translations/es.json, custom_components/thermal_comfort/translations/fr.json, custom_components/thermal_comfort/translations/hu.json, custom_components/thermal_comfort/translations/it.json, custom_components/thermal_comfort/translations/nl.json, custom_components/thermal_comfort/translations/pl.json, custom_components/thermal_comfort/translations/pt-BR.json, custom_components/thermal_comfort/translations/pt.json, custom_components/thermal_comfort/translations/ro.json, custom_components/thermal_comfort/translations/ru.json, custom_components/thermal_comfort/translations/sv.json, custom_components/thermal_comfort/translations/uk.json, custom_components/thermal_comfort/translations/zh-Hans.json
Preview the messages on https://inlang.com/github.com/rennokki/thermal_comfort
Some of the remaining translations were added for RO.
=> [RO] Update translations

custom_components/thermal_comfort/translations/it.json
Describe the changes you have conducted here
Preview the messages on https://inlang.com/github.com/Menelao147/thermal_comfort .
=> Update italian translations

project.inlang/settings.json
add urdu to inlang, so that it can be added as a translation.
=> Add Urdu in inlang

custom_components/thermal_comfort/translations/ur.json
Describe the changes you have conducted here
Preview the messages on https://inlang.com/github.com/yousaf465/thermal_comfort .
Urdu translation done.
=> Update Urdu translations

custom_components/thermal_comfort/translations/pt-BR.json, custom_components/thermal_comfort/translations/pt.json, custom_components/thermal_comfort/translations/sv.json
Brazilian Portuguese Localization(pt-br), also corrected some mistake in European Portuguese (pt-pt).
=> inlang: update translations

custom_components/thermal_comfort/translations/pl.json
Added some missing translations.
Preview the messages on https://inlang.com/github.com/MorganMLGman/thermal_comfort .
=> Update translations pl

custom_components/thermal_comfort/translations/nl.json
I've changed quite some translations for Dutch and added some missing translations.
Preview the messages on https://inlang.com/github.com/Xander-V/thermal_comfort .
=> Update translations nl-nl

custom_components/thermal_comfort/sensor.py, custom_components/thermal_comfort/translations/ca.json, custom_components/thermal_comfort/translations/cs.json, custom_components/thermal_comfort/translations/da.json, custom_components/thermal_comfort/translations/de.json, custom_components/thermal_comfort/translations/el.json, custom_components/thermal_comfort/translations/en.json, custom_components/thermal_comfort/translations/es.json, custom_components/thermal_comfort/translations/fr.json, custom_components/thermal_comfort/translations/hu.json, custom_components/thermal_comfort/translations/it.json, custom_components/thermal_comfort/translations/ja.json, custom_components/thermal_comfort/translations/nl.json, custom_components/thermal_comfort/translations/pl.json, custom_components/thermal_comfort/translations/pt-BR.json, custom_components/thermal_comfort/translations/pt.json, custom_components/thermal_comfort/translations/ro.json, custom_components/thermal_comfort/translations/ru.json, custom_components/thermal_comfort/translations/sk.json, custom_components/thermal_comfort/translations/ur.json, custom_components/thermal_comfort/translations/zh-Hans.json, tests/test_sensor.py
Hi - first PR for me. I noted a typo in the summer/winter perception name, so have corrected. I'd like to test, however I'm worried that all my automations will break if I remove your repository from my HA/HACS and add mine.
The code change should be fairly straightforward though - I did a global find/replace.
=> Typo in the perception name

custom_components/thermal_comfort/__init__.py
Fixes #376
Fixes #374
Tested with HA 2024.5.3
=> avoid deprecated method call

custom_components/thermal_comfort/translations/es.json, custom_components/thermal_comfort/translations/fr.json
Added & Corrected some french (commit 1) & spanish (commit 2) translations
=> Update French & Spanish translations

custom_components/thermal_comfort/__init__.py
Fixes: #414 -> await async_forward_entry_setups.
=> Fix: Update __init__.py

.github/workflows/add_archive_to_release.yml, custom_components/thermal_comfort/manifest.json
following the discussion  https://github.com/dolezsa/thermal_comfort/discussions/407
=> Fix version number
